USE LEARNDBMP04;

CREATE TABLE dbo.Products (
	  ID	 INT			IDENTITY (1, 1) NOT NULL
	, [Name] NVARCHAR(50)	NULL
	, Price  NVARCHAR(50)	NULL
	, [Date] DATETIME		NULL
	CONSTRAINT pk_id PRIMARY KEY (ID)
);